config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
    # controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  # resources :users, only: [:show] do
  #   resources :comments
  # end

  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'
  get 'dashboard' => 'pages#dashboard', as: 'dashboard'
  get 'newest_post' => 'pages#newest_post', as: 'newest_post'
  
  get 'settings/unsubscribe'
  patch 'settings/update'

  resources :users, only: [:show, :update]
  resources :posts do 
    resources :comments
  end
  
end

app/views/shared/_banner.html.erb
<header class="main-header">
  <div class="">
    <div class="row">
      <div class="col">
        <div class="text-center">
          <h1 class="m-0"><%= link_to 'Borderline Basic', home_path, {:class => "title"}  %></h1>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col mb-3">
        <div class="text-center sub-title ">
          <p class="m-0">The chronicles of a Borderline Basic B*tch</p>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="main-footer" class="mt-5 pt-5 pb-5">
  <hr>
  <div class="pt-3">
    <div class="container">
      <div class="row">
        <div class="col">
          <p class="text-center pt-3 sub-title">
            All rights reserved &copy; <span id="year"></span>  Borderline Basic
          </p>
        </div>
      </div>
    </div>
  </div>  
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse ml-auto" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <% if policy(Post).new? %>
        <li class="nav-item"> 
          <%= link_to "Create Post", new_post_path, class: "nav-link pr-4"  %> 
        </li>
      <% end %>
        <li class="nav-item dropdown pr-4">
          <% if current_user.facebook_picture_url? %>
            <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% elsif current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, transformation: [{width: 1000, height: 1000, gravity: "face", radius: "max", crop: "crop"}, {width: 200, crop: "scale"}],class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%=  image_tag "default_avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if policy(Post).new? %>
              <%= link_to "Create Post", new_post_path, class: "dropdown-item"  %> 
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "My Account", edit_user_registration_path, class: "dropdown-item"  %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to " Login", new_user_session_path, class: "nav-link far fa-user" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>