config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
    # controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  # resources :users, only: [:show] do
  #   resources :comments
  # end

  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'
  get 'dashboard' => 'pages#dashboard', as: 'dashboard'
  get 'newest_post' => 'pages#newest_post', as: 'newest_post'
  
  get 'settings/unsubscribe'
  patch 'settings/update'

  resources :users, only: [:show, :update]
  resources :posts do 
    resources :comments
  end
  
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :skip_authorization
  skip_before_action :authenticate_user!

  def unsubscribe
    user = Rails.application.message_verifier(:unsubscribe).verify(params[:id])
    @user = User.find(user)
    # @user = User.second
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'Subscription Cancelled' 
      redirect_to home_path
    else
      flash[:alert] = 'There was a problem'
      render :unsubscribe
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:subscribed)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/unsubscribe.html.erb
<%= render "shared/banner" %>

<div class="row d-flex justify-content-center">
  <div class="col-sm-12 col-md-8 col-lg-5">
    <div class="form-login">
      <h2 class="text-center pt-3 pb-0 mb-1">Unsubscribe </h2>
      <div class="">
        <div class="post-text mb-5 text-center">
          <p class="pt-0 mt-0">By unsubscribing, you will no longer receive emails...</p>
          <%= form_for(@user, url: settings_update_path(id: @user.id)) do |f| %>
            <%= f.hidden_field(:subscribed, value: false) %>
            <div class="row mt-4">
              <div class="col mt-2">
                <%= f.submit 'Unsubscribe', class: "btn btn-outline-primary" %>
                <%= link_to 'Cancel', home_path, class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>  
      </div>
    </div>
  </div>
</div>