config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
    # controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  # resources :users, only: [:show] do
  #   resources :comments
  # end

  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'
  get 'dashboard' => 'pages#dashboard', as: 'dashboard'
  get 'newest_post' => 'pages#newest_post', as: 'newest_post'
  
  get 'settings/unsubscribe'
  patch 'settings/update'

  resources :users, only: [:show, :update]
  resources :posts do 
    resources :comments
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  after_create :send_new_post_email
  # after_update :send_new_post_email

  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 1}

  private
  
  def send_new_post_email
    unless self.draft
      UserMailer.new_post_request
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show] 
  before_action :set_user, only: [:show]
  # before_action :check_if_published, only: [:show]

  def index
    @posts = policy_scope(Post).order(publish_date: :desc)
    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    authorize @post
  end
  
  def new
    @post = Post.new
    
    authorize @post
  end

  def create
    
    if params[:draft]
      @post = Post.new(post_params)
      set_publish_date
      @post.user = current_user
      @post.write_attribute(:draft, true)
      authorize @post
    else
      @post = Post.new(post_params)
      set_publish_date
      @post.user = current_user
      @post.write_attribute(:draft, false)
      set_publish_date
      authorize @post
    end
    
    # @post = Post.new(post_params)
    # @post.user = current_user
    # authorize @post

    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    if params[:draft]
      @post = Post.find(params[:id])
      @post.user = current_user
      @post.write_attribute(:draft, true)
      authorize @post
    else
      @post = Post.find(params[:id])
      @post.user = current_user
      if @post.draft?
        @post.write_attribute(:draft, false)
        set_publish_date
        send_new_post_email
      end
      authorize @post
    end

    # @post = Post.find(params[:id])
    # authorize @post

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post
    @post.destroy

    redirect_to dashboard_path
  end

  private 
  
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def set_user
    @user ||= ((User.find(session[:user_id]) if session[:user_id]) || User.new)
  end

  def set_publish_date
    @post.write_attribute(:publish_date, Time.now)
  end

  def send_new_post_email
    # unless self.draft
      UserMailer.new_post_request
    # end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<%= render "shared/banner" %>

<!-- <h1>Edit post</h1> -->
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.cktext_area(:body, {:class => 'form-control'}) %>
  </p>
  <div class="row">
    <div class="col text-right">
      <p class="d-inline">
        <%= f.submit "Publish!", class: 'btn btn-outline-primary', :name => "publish"  %>
      </p>
    <!-- </div>
    <div class="col"> -->
      <p class="d-inline">
        <%= f.submit "Save Draft!", class: 'btn btn-primary', :name => "draft"  %>
      </p>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= render "shared/banner" %>


<div class="row banner-padding">
  <div class="col">
    <div class="d-flex justify-content-around">
      <div class="home-posts">
        <% @posts.each do |post| %>
          <% unless post.draft %>
          <div class="individual-post mb-4 pb-5">
            <h3 class="post-title"><%= link_to post.title , post_path(post), {:class => 'header' } %></h3>
            <div class="post-text">
              <p class="mb-0" ></p><%= sanitize post.body.truncate(2500) %></p>
              <div class="text-right">
                <div  class=""> <%= link_to 'Continue Reading' , post_path(post), {:class => 'btn bb-btn btn-sm btn-outline-primary' } %> </div>
              </div>
            </div>  
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render "shared/banner" %>

<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.cktext_area(:body, {:class => 'form-control'}) %>
  </p>
  <div class="row">
    <div class="col text-right">
      <p class="d-inline">
        <%= f.submit "Publish!", class: 'btn btn-outline-primary', :name => "publish"  %>
      </p>
    <!-- </div>
    <div class="col"> -->
      <p class="d-inline">
        <%= f.submit "Save Draft!", class: 'btn btn-primary', :name => "draft"  %>
      </p>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= render "shared/banner" %>

<div class="row banner-padding">
  <div class="col">
    <div class="d-flex justify-content-around">
      <div class="home-posts">
        <div class="text-center">
          <h3><%= @post.title %></h3>
        </div>
        <div class="post-text mb-5">
          <p><%= sanitize @post.body %></p>
          <p class="post-date" ><%=  @post.publish_date.strftime("%B %d, %Y") %></p>
        </div>  
        <hr>

        <div id="comments" class="mt-3">
          <h3  class="text-center comment-title my-3">Comments</h3>
          <div class="my-2"><%= render 'comments/form'%></div>
          <div class="my-2"><%= render 'comments/comments' %></div>
        </div>
      </div>
    </div>
  </div>
</div>